### PR TITLE
[G2M] 09 - set operations

### PR DESCRIPTION
**Pull request by bsandi1220**

### CODE REVIEW

**Review by maluhoss — COMMENTED** [review]
Looks great! this is such a good example of illustrating the diff between union, minus and intersect. this is also in segments page so this would help people better understand how combining segments work too! A few recommendations (I tried to split by header):

- define what an audience is - essentially a list of device IDs with other metadata like data (this can get pretty confusing later)

Generate audiences
- would add more context to this line: "Using the defined POIs, we will get the audiences for Loblaws POIs from March 15th and March 16th with a 100m radius"
- also mention that get_audience is for 1 day

Union All datasets
- make 'Automate the Union and Date generation' a subheader maybe?
- should have a line explaining what you mean by automating union and date generation - example:
  - manually running one line to get the audience for one date & a second line to combine each audience together is tedious so we will automate this by: 1) automatically generating a range of dates we are interested in using a function get_dates 2) Using these list of dates, get audience for each date 3) combining all of these audiences into one big audience
- suggest having function get_dates before mentioning the datetime functions you'll use (i was confused as to why i was seeing this functions, then it made more sense after seeing get_dates)
- functions is spelled wrong in 'We will be using some of the functions datetime and timedelta to work with dates'
- should be 'We will loop over the generated dates and build AN audience for each one'
- Instead of 'Using concat we can Union All the audiences and check some metrics on those.', suggest making it simpler by saying 'Using concat, we can unify all the device IDs from Loblaws, Sobeys and Longos into one list' or something
- Add a comment saying 'The length of the entire audience is:' before len(union_audience)
- Add another comment saying 'The length of unique device IDs in the audience is:' before the unique() line
- What does nunique exactly mean in this context when you've unified all the device IDS from each POI list?
- Could use a few lines after the heatmap to explain what they're seeing

Intersection in Datsets
- A little confused by the line 'In other words, if the device X has been to 2 locations, we will register 4 different combinations' - why is that?
- should be 'We can create an audience that have walkED to Longos first and after that to Sobeys, if the order is something we are interested in.'
- should be 'If the number of visits IS important for our analysis we could include a preprocessing step before performing the Union All'
- when you mention 'First we will get the counts per device' - maybe explain a bit how you're doing this part
- maybe mention how you got the column names. - I did a double take to see how these were created.

**Comment by bsandi1220** [comment]
Updated with your comments @maluhoss 

`What does nunique exactly mean in this context when you've unified all the device IDS from each POI list?
`It is a count of the unique values

`A little confused by the line 'In other words, if the device X has been to 2 locations, we will register 4 different combinations' - why is that?`
If device x has been to location A and B from list 1, and C and D from list 2. 
 We will register the combinations A-C A-D B-C B-D

**Review by maluhoss — COMMENTED** [review]
looks good! just 2 comments:
- would add a line explaining what you just told me about nunique - it's not as intuitive at first
- one summary line of what you see in the heatmap. it just helps as a reader

**Comment by woozyking** [comment]
noice. i've removed the regular recurring session due to my vacation, if this is not to be carried out in TC on Thursday, could you set one up for Friday at the same time slot and invite the usual attendants (and/or the participants in the Slack channel)?

**Comment by bsandi1220** [comment]
Sure, will send the invite for Friday. @woozyking 

Added the changes. @maluhoss

**Review by maluhoss — APPROVED** [review]

**Pull request merged**
